import { createAdminClient } from "@/lib/supabase/admin";
import { requireAdmin } from "@/lib/auth";
import { Eye, MousePointerClick, Megaphone, IndianRupee } from "lucide-react";

const money=(n:number)=>`₹${Number(n||0).toLocaleString("en-IN")}`;
export default async function AdminSponsorships(){
  await requireAdmin("sponsorships.view"); const db=createAdminClient();
  const {data}=await db.from("sponsorship_campaigns").select("id,user_id,product_id,placement_id,status,amount_inr,payment_id,starts_at,ends_at,impressions,clicks,rejection_reason,reviewed_at,created_at").order("created_at",{ascending:false}).limit(200);
  const rows=data??[], active=rows.filter(x=>x.status==="active"), pending=rows.filter(x=>x.status==="pending"||x.status==="submitted"), revenue=rows.reduce((s,x)=>s+Number(x.amount_inr||0),0), impressions=rows.reduce((s,x)=>s+Number(x.impressions||0),0), clicks=rows.reduce((s,x)=>s+Number(x.clicks||0),0);
  return <div className="admin-page">
    <div className="admin-heading"><p className="eyebrow">Monetization / sponsorships</p><h1>Sponsorships.</h1><p>Review sponsored placements and monitor their delivery and engagement.</p></div>
    <div className="admin-stat-grid admin-stat-grid-detailed admin-stat-grid-4"><div className="admin-kpi"><div className="admin-kpi-top"><span>Active</span><Megaphone size={16}/></div><strong>{active.length}</strong><small>live campaigns</small></div><div className="admin-kpi"><div className="admin-kpi-top"><span>Review</span><Megaphone size={16}/></div><strong>{pending.length}</strong><small>pending campaigns</small></div><div className="admin-kpi"><div className="admin-kpi-top"><span>Impressions</span><Eye size={16}/></div><strong>{impressions}</strong><small>recorded delivery</small></div><div className="admin-kpi"><div className="admin-kpi-top"><span>Clicks</span><MousePointerClick size={16}/></div><strong>{clicks}</strong><small>{impressions?Math.round(clicks/impressions*10000)/100:0}% CTR</small></div></div>
    <section className="admin-card"><div className="admin-section-head"><div><p className="eyebrow">Sponsored inventory</p><h2>Campaign ledger</h2></div><strong className="admin-value">{money(revenue)}</strong></div>
      <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Campaign</th><th>Status</th><th>Investment</th><th>Delivery</th><th>Window</th><th>Review</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td><strong>{x.product_id.slice(0,10)}…</strong><small>Owner {x.user_id.slice(0,10)}… · placement {x.placement_id.slice(0,8)}…</small></td><td><span className={"admin-status "+(x.status==="active"?"success":x.status==="rejected"?"danger":"warning")}>{x.status}</span></td><td><strong>{money(x.amount_inr)}</strong></td><td><strong>{x.impressions||0}</strong> impressions<small>{x.clicks||0} clicks</small></td><td><small>{x.starts_at?new Date(x.starts_at).toLocaleDateString("en-IN"):"—"} → {x.ends_at?new Date(x.ends_at).toLocaleDateString("en-IN"):"—"}</small></td><td><small>{x.reviewed_at?new Date(x.reviewed_at).toLocaleString("en-IN"):"Not reviewed"}</small></td></tr>)}</tbody></table>{!rows.length&&<div className="admin-empty">No sponsorship campaigns found.</div>}</div>
    </section>
  </div>;
}