import Link from "next/link";
import { ArrowUp, ChevronRight, MessageCircle, Pin, Search, Sparkles } from "lucide-react";
import type { CommunityForum, CommunityThread } from "@/lib/community";
import { CommunityVoteButton } from "@/components/projecthub/community-vote-button";
import { ProfileBadge } from "@/components/projecthub/profile-badge";

export function CommunitySidebar({forums,activeSlug}:{forums:CommunityForum[];activeSlug?:string}){
 return <aside className="community-sidebar"><div className="community-sidebar-head"><span className="community-sidebar-label">Forums</span><Sparkles size={15}/></div><nav className="community-forum-nav"><Link href="/community" className={"community-forum-link "+(!activeSlug?"is-active":"")}><span className="community-forum-icon">✦</span><span>All discussions</span></Link>{forums.map(f=><Link key={f.id} href={"/community/f/"+f.slug} className={"community-forum-link "+(activeSlug===f.slug?"is-active":"")}><span className="community-forum-icon">{f.icon||"•"}</span><span>{f.name}</span></Link>)}</nav><div className="community-sidebar-note">Ask questions, share progress, give feedback, and help other makers build better products.</div></aside>;
}
function authorName(thread:CommunityThread){return thread.author?.display_name||thread.author?.username||thread.author?.name||"ProjectHub member"}
function timeAgo(dateString:string){const seconds=Math.max(0,Math.floor((Date.now()-new Date(dateString).getTime())/1000));if(seconds<60)return"just now";const minutes=Math.floor(seconds/60);if(minutes<60)return minutes+"m ago";const hours=Math.floor(minutes/60);if(hours<24)return hours+"h ago";const days=Math.floor(hours/24);if(days<30)return days+"d ago";return Math.floor(days/30)+"mo ago"}
export function CommunityThreadList({threads}:{threads:CommunityThread[]}){
 return <div className="community-thread-list">{threads.map(thread=><article key={thread.id} className="community-thread-row"><CommunityVoteButton threadId={thread.id} initialCount={thread.vote_count} initialVoted={thread.viewer_voted}/><div className="community-thread-main"><div className="community-thread-meta">{thread.is_pinned&&<span className="community-thread-badge"><Pin size={12}/>Pinned</span>}{thread.forum&&<Link href={"/community/f/"+thread.forum.slug}>{thread.forum.name}</Link>}<span>•</span><span>{timeAgo(thread.last_activity_at)}</span></div><Link href={"/community/t/"+thread.id} className="community-thread-title">{thread.title}</Link><p>{thread.content.length>170?thread.content.slice(0,170).trimEnd()+"…":thread.content}</p><div className="community-thread-footer">{thread.author?.username?<Link href={"/u/"+thread.author.username} className="community-author-inline">{authorName(thread)}{thread.author?.tier&&<ProfileBadge tier={thread.author.tier}/>}</Link>:<span className="community-author-inline">{authorName(thread)}{thread.author?.tier&&<ProfileBadge tier={thread.author.tier}/>}</span>}<span className="community-thread-stat"><MessageCircle size={14}/>{thread.reply_count} {thread.reply_count===1?"reply":"replies"}</span><span className="community-thread-stat">{thread.views} views</span></div></div><Link className="community-thread-arrow" href={"/community/t/"+thread.id} aria-label={"Open "+thread.title}><ChevronRight size={18}/></Link></article>)}</div>;
}
export function CommunitySearch({search,sort,forumSlug}:{search:string;sort:string;forumSlug?:string}){return <form className="community-search" action={forumSlug?"/community/f/"+forumSlug:"/community"}><Search size={17}/><input name="q" defaultValue={search} placeholder="Search discussions..." aria-label="Search community discussions"/>{forumSlug&&<input type="hidden" name="sort" value={sort}/>}<button type="submit">Search</button></form>}
export function CommunitySortTabs({sort,forumSlug,search}:{sort:"trending"|"popular"|"new";forumSlug?:string;search?:string}){const href=(value:string)=>{const base=forumSlug?"/community/f/"+forumSlug:"/community";const params=new URLSearchParams();if(search)params.set("q",search);params.set("sort",value);return base+"?"+params.toString()};return <div className="community-sort"><ArrowUp size={15}/><Link className={sort==="trending"?"is-active":""} href={href("trending")}>Trending</Link><Link className={sort==="popular"?"is-active":""} href={href("popular")}>Popular</Link><Link className={sort==="new"?"is-active":""} href={href("new")}>New</Link></div>}
