"use client";

import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { Bell, ChevronDown, CreditCard, FolderKanban, Gavel, LayoutDashboard, LogOut, Megaphone, Menu, Search, Settings, ShieldCheck, UserRound, X } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
import { usePathname, useRouter } from "next/navigation";
import type { ProfileTier } from "@/lib/profile";
import { ProfileBadge } from "@/components/projecthub/profile-badge";

const links=[["Explore","/explore"],["Launch","/launch"],["Promote","/promote"],["Community","/community"],["Newsletter","/newsletter"]];
type AuthUser={id:string;displayName:string;username:string;avatarUrl:string|null;tier:ProfileTier;isAdmin:boolean};
const workspaceLinks=[["Dashboard","/dashboard",LayoutDashboard],["Projects","/dashboard/projects",FolderKanban],["Promotions","/dashboard/promotions",Megaphone],["Auctions","/dashboard/auctions",Gavel],["Payments","/dashboard/payments",CreditCard]] as const;

export function NavbarClient({user,unreadCount=0}:{user:AuthUser|null;unreadCount?:number}){
 const [open,setOpen]=useState(false),[accountOpen,setAccountOpen]=useState(false),[signingOut,setSigningOut]=useState(false),[searchOpen,setSearchOpen]=useState(false),[query,setQuery]=useState("");
 const accountRef=useRef<HTMLDivElement>(null),searchInputRef=useRef<HTMLInputElement>(null); const router=useRouter(),pathname=usePathname();
 useEffect(()=>{if(!accountOpen)return;const onPointer=(e:PointerEvent)=>{if(!accountRef.current?.contains(e.target as Node))setAccountOpen(false)};const onKey=(e:KeyboardEvent)=>{if(e.key==="Escape")setAccountOpen(false)};document.addEventListener("pointerdown",onPointer);document.addEventListener("keydown",onKey);return()=>{document.removeEventListener("pointerdown",onPointer);document.removeEventListener("keydown",onKey)}},[accountOpen]);
 useEffect(()=>{const current=new URLSearchParams(window.location.search).get("q")||"";if(pathname==="/explore")setQuery(current)},[pathname]);
 useEffect(()=>{if(searchOpen){requestAnimationFrame(()=>searchInputRef.current?.focus())}},[searchOpen]);
 async function signOut(){if(signingOut)return;setSigningOut(true);await createClient().auth.signOut();setAccountOpen(false);setOpen(false);router.push("/");router.refresh()}
 function submitSearch(e:React.FormEvent){e.preventDefault();const q=query.trim();setSearchOpen(false);if(q)router.push("/explore?q="+encodeURIComponent(q));else router.push("/explore");}
 const initials=(user?.displayName||user?.username||"U").slice(0,1).toUpperCase(),name=user?.displayName||user?.username||"Member",handle=user?.username?"@"+user.username:"ProjectHub member";
 return <header className="site-header"><div className="shell nav-inner"><Link href="/" className="wordmark">Project<span>Hub</span></Link>
 <nav className="desktop-nav">{links.map(([label,href])=><Link key={href} href={href}>{label}</Link>)}
   {!searchOpen?<button type="button" className="nav-search-trigger" onClick={()=>setSearchOpen(true)} aria-label="Search projects"><Search size={15}/>Search</button>:<form className="nav-search-form" onSubmit={submitSearch} role="search"><Search size={15}/><input ref={searchInputRef} value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==="Escape"){setSearchOpen(false);setQuery(pathname==="/explore"?query:"")}}} placeholder="Search projects..." aria-label="Search projects"/><button type="button" className="nav-search-close" onClick={()=>setSearchOpen(false)} aria-label="Close search"><X size={14}/></button></form>}
 </nav>
 <div className="nav-actions">{user&&<Link href="/notifications" className="nav-notifications" aria-label={unreadCount>0?unreadCount+" unread notifications":"Notifications"}><Bell size={17}/>{unreadCount>0&&<span aria-hidden="true" />}</Link>}{user?<div className="account-menu" ref={accountRef}>
  <button type="button" className={"account-trigger"+(accountOpen?" is-open":"")} aria-expanded={accountOpen} aria-haspopup="menu" aria-label="Open account menu" onClick={()=>setAccountOpen(v=>!v)}><span className="account-avatar">{user.avatarUrl?<img src={user.avatarUrl} alt=""/>:initials}</span><span className="account-trigger-copy"><strong>{name}</strong><small>{handle}</small></span><ProfileBadge tier={user.tier}/><ChevronDown className="account-chevron" size={14}/></button>
  {accountOpen&&<div className="account-dropdown" role="menu"><div className="account-dropdown-head"><span className="account-avatar account-avatar-large">{user.avatarUrl?<img src={user.avatarUrl} alt=""/>:initials}</span><div className="account-dropdown-identity"><strong>{name}<ProfileBadge tier={user.tier}/></strong><span>{handle}</span><small className="account-role-label">{user.tier.label}</small></div></div>
   <div className="account-dropdown-section-label">Profile</div><div className="account-single-link"><Link href="/profile" role="menuitem" onClick={()=>setAccountOpen(false)}><span className="account-link-icon"><UserRound size={15}/></span><span><strong>Profile</strong><small>{user.tier.label}</small></span></Link></div>
   <div className="account-dropdown-section-label">Workspace</div><div className="account-links">{workspaceLinks.map(([label,href,Icon])=><Link href={href} role="menuitem" key={href} onClick={()=>setAccountOpen(false)}><span className="account-link-icon"><Icon size={15}/></span><span>{label}</span></Link>)}<Link href="/dashboard/settings" role="menuitem" onClick={()=>setAccountOpen(false)}><span className="account-link-icon"><Settings size={15}/></span><span>Settings</span></Link>{user.isAdmin&&<Link href="/admin" role="menuitem" onClick={()=>setAccountOpen(false)}><span className="account-link-icon"><ShieldCheck size={15}/></span><span>Admin Control Room</span></Link>}</div>
   <div className="account-divider"/><Link href="/launch" role="menuitem" className="account-launch-link" onClick={()=>setAccountOpen(false)}><span>Launch a new project</span><span>↗</span></Link><button type="button" role="menuitem" className="account-signout" onClick={signOut} disabled={signingOut}><LogOut size={15}/>{signingOut?"Signing out...":"Log out"}</button>
  </div>}</div>:<Link href="/login" className="nav-text">Log in</Link>}<Link href="/launch" className="nav-cta">Launch Project</Link></div>
 <button className="mobile-menu" onClick={()=>setOpen(v=>!v)} aria-label={open?"Close menu":"Open menu"}>{open?<X/>:<Menu/>}</button></div>
 {open&&<div className="mobile-panel">{user&&<Link href="/notifications" onClick={()=>setOpen(false)} className="mobile-notifications"><Bell size={15}/>Notifications{unreadCount>0&&<span aria-hidden="true" />}</Link>}{links.map(([label,href])=><Link key={href} href={href} onClick={()=>setOpen(false)}>{label}</Link>)}
   {!searchOpen?<button type="button" className="mobile-search-trigger" onClick={()=>setSearchOpen(true)}><Search size={15}/>Search</button>:<form className="mobile-search-form" onSubmit={submitSearch} role="search"><Search size={15}/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search projects..." aria-label="Search projects"/><button type="button" onClick={()=>setSearchOpen(false)} aria-label="Close search"><X size={14}/></button></form>}
 {user?<><div className="mobile-account-card"><span className="account-avatar">{user.avatarUrl?<img src={user.avatarUrl} alt=""/>:initials}</span><div><strong>{name}<ProfileBadge tier={user.tier}/></strong><span>{handle}</span><small>{user.tier.label}</small></div></div><div className="mobile-profile-link"><Link href="/profile" onClick={()=>setOpen(false)}><UserRound size={15}/>Profile</Link></div><div className="mobile-account-links">{workspaceLinks.map(([label,href,Icon])=><Link href={href} key={href} onClick={()=>setOpen(false)}><Icon size={15}/>{label}</Link>)}<Link href="/dashboard/settings" onClick={()=>setOpen(false)}><Settings size={15}/>Settings</Link>{user.isAdmin&&<Link href="/admin" onClick={()=>setOpen(false)}><ShieldCheck size={15}/>Admin Control Room</Link>}</div><button type="button" className="mobile-signout" onClick={signOut} disabled={signingOut}><LogOut size={15}/>{signingOut?"Signing out...":"Log out"}</button></>:<Link href="/login" onClick={()=>setOpen(false)}>Log in</Link>}<Link href="/launch" className="nav-cta" onClick={()=>setOpen(false)}>Launch Project</Link></div>}</header>;
}
