create extension if not exists pgcrypto;

create schema if not exists private;
create type public.user_role as enum ('user','admin');
create type public.project_status as enum ('draft','pending_review','published','rejected','archived');
create type public.promotion_status as enum ('pending','scheduled','active','expired','cancelled');
create type public.auction_status as enum ('scheduled','active','ended','cancelled','settled');
create type public.payment_status as enum ('created','pending','paid','failed','refunded','cancelled');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique, display_name text, avatar_url text, bio text,
  role public.user_role not null default 'user', is_public boolean not null default true,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

create table public.categories (
  id uuid primary key default gen_random_uuid(),
  name text not null unique, slug text not null unique, description text,
  created_at timestamptz not null default now()
);

create table public.tags (
  id uuid primary key default gen_random_uuid(), name text not null unique, slug text not null unique
);

create table public.projects (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.profiles(id) on delete cascade,
  name text not null, slug text not null unique, tagline text not null, description text not null,
  logo_url text, website_url text not null, category_id uuid not null references public.categories(id),
  social_links jsonb not null default '{}'::jsonb,
  status public.project_status not null default 'draft',
  published_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

create table public.project_tags (
  project_id uuid references public.projects(id) on delete cascade,
  tag_id uuid references public.tags(id) on delete cascade,
  primary key(project_id,tag_id)
);
create table public.project_views (
  id bigint generated by default as identity primary key,
  project_id uuid not null references public.projects(id) on delete cascade,
  viewer_id uuid references public.profiles(id) on delete set null,
  session_id text, created_at timestamptz not null default now()
);
create index project_views_project_created_idx on public.project_views(project_id,created_at desc);

create table public.project_clicks (
  id bigint generated by default as identity primary key,
  project_id uuid not null references public.projects(id) on delete cascade,
  viewer_id uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);
create index project_clicks_project_created_idx on public.project_clicks(project_id,created_at desc);

create table public.promotion_types (
  id uuid primary key default gen_random_uuid(),
  name text not null unique, slug text not null unique, description text,
  default_price numeric(12,2) not null check(default_price>=0),
  default_duration_days integer not null check(default_duration_days>0),
  created_at timestamptz not null default now()
);
create table public.promotion_positions (
  id uuid primary key default gen_random_uuid(),
  name text not null unique, slug text not null unique, description text,
  created_at timestamptz not null default now()
);
create table public.promotions (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  type_id uuid not null references public.promotion_types(id),
  position_id uuid not null references public.promotion_positions(id),
  amount numeric(12,2) not null check(amount>=0),
  duration_days integer not null check(duration_days>0),
  starts_at timestamptz, ends_at timestamptz,
  status public.promotion_status not null default 'pending',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index promotions_active_idx on public.promotions(status,starts_at,ends_at);

create table public.auctions (
  id uuid primary key default gen_random_uuid(),
  project_id uuid not null references public.projects(id) on delete cascade,
  position_id uuid not null references public.promotion_positions(id),
  starting_price numeric(12,2) not null check(starting_price>=0),
  current_bid numeric(12,2),
  bid_increment numeric(12,2) not null check(bid_increment>0),
  starts_at timestamptz not null, ends_at timestamptz not null,
  status public.auction_status not null default 'scheduled',
  winner_id uuid references public.profiles(id), winning_bid numeric(12,2),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  check(ends_at>starts_at),
  check(current_bid is null or current_bid>=starting_price)
);
create index auctions_status_ends_idx on public.auctions(status,ends_at);
create table public.auction_bids (
  id uuid primary key default gen_random_uuid(),
  auction_id uuid not null references public.auctions(id) on delete cascade,
  bidder_id uuid not null references public.profiles(id) on delete cascade,
  amount numeric(12,2) not null check(amount>0),
  created_at timestamptz not null default now()
);
create index auction_bids_auction_created_idx on public.auction_bids(auction_id,created_at desc);

create table public.payments (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  project_id uuid references public.projects(id) on delete set null,
  promotion_id uuid references public.promotions(id) on delete set null,
  auction_id uuid references public.auctions(id) on delete set null,
  razorpay_order_id text unique, razorpay_payment_id text unique,
  amount numeric(12,2) not null check(amount>=0),
  currency text not null default 'INR',
  status public.payment_status not null default 'created',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create index payments_user_created_idx on public.payments(user_id,created_at desc);

create table public.payment_events (
  id uuid primary key default gen_random_uuid(),
  provider text not null default 'razorpay',
  event_id text not null unique,
  payment_id uuid references public.payments(id) on delete set null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create table public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  type text not null, title text not null, body text not null,
  data jsonb not null default '{}'::jsonb, read_at timestamptz,
  created_at timestamptz not null default now()
);

create table public.admin_actions (
  id uuid primary key default gen_random_uuid(),
  admin_id uuid not null references public.profiles(id),
  action text not null, target_type text not null, target_id uuid,
  metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now()
);

create table public.settings (
  key text primary key, value jsonb not null, is_public boolean not null default false,
  updated_at timestamptz not null default now()
);

create function private.touch_updated_at() returns trigger
language plpgsql as $func$
begin new.updated_at=now(); return new; end
$func$;

create trigger profiles_touch before update on public.profiles for each row execute function private.touch_updated_at();
create trigger projects_touch before update on public.projects for each row execute function private.touch_updated_at();
create trigger promotions_touch before update on public.promotions for each row execute function private.touch_updated_at();
create trigger auctions_touch before update on public.auctions for each row execute function private.touch_updated_at();
create trigger payments_touch before update on public.payments for each row execute function private.touch_updated_at();
create trigger settings_touch before update on public.settings for each row execute function private.touch_updated_at();
create function private.is_admin() returns boolean
language sql stable
as $func$
  select coalesce((auth.jwt()->'app_metadata'->>'role')='admin',false);
$func$;

create view public.project_directory
with (security_invoker=true) as
select p.id,p.owner_id as creator_id,p.slug,p.name,p.tagline,p.description,
  p.logo_url,p.website_url,p.social_links,p.status,p.created_at,p.published_at,
  c.id as category_id,c.name as category_name,c.slug as category_slug,
  pr.display_name as creator_name,
  coalesce(array_agg(distinct t.name) filter(where t.name is not null),'{}') as tags,
  exists(
    select 1 from public.promotions x
    join public.promotion_types pt on pt.id=x.type_id
    where x.project_id=p.id and x.status='active' and pt.slug='featured'
  ) as featured,
  exists(
    select 1 from public.promotions x
    join public.promotion_positions pp on pp.id=x.position_id
    where x.project_id=p.id and x.status='active'
      and pp.slug like 'homepage%'
  ) as promoted
from public.projects p
join public.categories c on c.id=p.category_id
join public.profiles pr on pr.id=p.owner_id
left join public.project_tags ptg on ptg.project_id=p.id
left join public.tags t on t.id=ptg.tag_id
group by p.id,c.id,pr.id;
alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.tags enable row level security;
alter table public.projects enable row level security;
alter table public.project_tags enable row level security;
alter table public.project_views enable row level security;
alter table public.project_clicks enable row level security;
alter table public.promotion_types enable row level security;
alter table public.promotion_positions enable row level security;
alter table public.promotions enable row level security;
alter table public.auctions enable row level security;
alter table public.auction_bids enable row level security;
alter table public.payments enable row level security;
alter table public.payment_events enable row level security;
alter table public.notifications enable row level security;
alter table public.admin_actions enable row level security;
alter table public.settings enable row level security;

grant select on public.categories,public.tags,public.promotion_types,public.promotion_positions,public.auctions to anon,authenticated;
grant select on public.project_directory to anon,authenticated;
grant select,insert,update on public.profiles to authenticated;
grant select,insert,update,delete on public.projects,public.project_tags to authenticated;
grant insert on public.project_views,public.project_clicks to anon,authenticated;
grant select,insert on public.promotions to authenticated;
grant select on public.payments,public.auction_bids,public.notifications to authenticated;
grant insert,update on public.notifications to authenticated;
grant select,insert,update on public.admin_actions to authenticated;
grant select on public.settings to anon,authenticated;

create policy profiles_public_read on public.profiles
for select to anon,authenticated
using (is_public or id=(select auth.uid()) or private.is_admin());

create policy profiles_self_write on public.profiles
for update to authenticated
using (id=(select auth.uid()) or private.is_admin())
with check (id=(select auth.uid()) or private.is_admin());

create policy categories_read on public.categories for select to anon,authenticated using(true);
create policy categories_admin on public.categories for all to authenticated
using(private.is_admin()) with check(private.is_admin());

create policy tags_read on public.tags for select to anon,authenticated using(true);
create policy tags_admin on public.tags for all to authenticated
using(private.is_admin()) with check(private.is_admin());
create policy projects_public_read on public.projects
for select to anon,authenticated
using (status='published' or owner_id=(select auth.uid()) or private.is_admin());

create policy projects_owner_insert on public.projects
for insert to authenticated
with check (owner_id=(select auth.uid()) or private.is_admin());

create policy projects_owner_update on public.projects
for update to authenticated
using (owner_id=(select auth.uid()) or private.is_admin())
with check (owner_id=(select auth.uid()) or private.is_admin());

create policy projects_owner_delete on public.projects
for delete to authenticated
using (owner_id=(select auth.uid()) or private.is_admin());

create policy project_tags_read on public.project_tags
for select to anon,authenticated
using (
  exists(select 1 from public.projects p
    where p.id=project_id
      and (p.status='published' or p.owner_id=(select auth.uid()) or private.is_admin()))
);

create policy project_tags_write on public.project_tags
for all to authenticated
using (
  exists(select 1 from public.projects p
    where p.id=project_id
      and (p.owner_id=(select auth.uid()) or private.is_admin()))
)
with check (
  exists(select 1 from public.projects p
    where p.id=project_id
      and (p.owner_id=(select auth.uid()) or private.is_admin()))
);

create policy project_views_insert on public.project_views
for insert to anon,authenticated
with check (viewer_id is null or viewer_id=(select auth.uid()));

create policy project_views_owner_read on public.project_views
for select to authenticated
using (
  exists(select 1 from public.projects p
    where p.id=project_id
      and (p.owner_id=(select auth.uid()) or private.is_admin()))
);

create policy project_clicks_insert on public.project_clicks
for insert to anon,authenticated
with check (viewer_id is null or viewer_id=(select auth.uid()));

create policy project_clicks_owner_read on public.project_clicks
for select to authenticated
using (
  exists(select 1 from public.projects p
    where p.id=project_id
      and (p.owner_id=(select auth.uid()) or private.is_admin()))
);

create policy promotion_types_admin on public.promotion_types for all to authenticated
using(private.is_admin()) with check(private.is_admin());

create policy promotion_positions_admin on public.promotion_positions for all to authenticated
using(private.is_admin()) with check(private.is_admin());
create policy promotions_owner_read on public.promotions
for select to authenticated using(user_id=(select auth.uid()) or private.is_admin());

create policy promotions_owner_insert on public.promotions
for insert to authenticated with check(user_id=(select auth.uid()) or private.is_admin());

create policy auctions_public_read on public.auctions
for select to anon,authenticated using(true);

create policy auction_bids_owner_insert on public.auction_bids
for insert to authenticated with check(bidder_id=(select auth.uid()));

create policy auction_bids_owner_read on public.auction_bids
for select to authenticated using(bidder_id=(select auth.uid()) or private.is_admin());

create policy payments_owner_read on public.payments
for select to authenticated using(user_id=(select auth.uid()) or private.is_admin());

create policy notifications_owner_read on public.notifications
for select to authenticated using(user_id=(select auth.uid()) or private.is_admin());

create policy notifications_owner_update on public.notifications
for update to authenticated
using(user_id=(select auth.uid()) or private.is_admin())
with check(user_id=(select auth.uid()) or private.is_admin());

create policy admin_actions_admin on public.admin_actions
for all to authenticated
using(private.is_admin()) with check(private.is_admin());

create policy settings_public_read on public.settings
for select to anon,authenticated using(is_public or private.is_admin());

create policy settings_admin on public.settings for all to authenticated
using(private.is_admin()) with check(private.is_admin());
create or replace function public.place_bid(p_auction_id uuid,p_amount numeric)
returns public.auction_bids
language plpgsql
set search_path=public,pg_temp
as $func$
declare
  a public.auctions;
  b public.auction_bids;
  minimum numeric;
begin
  if (select auth.uid()) is null then
    raise exception 'Authentication required';
  end if;

  select * into a from public.auctions where id=p_auction_id for update;
  if not found then raise exception 'Auction not found'; end if;
  if a.status <> 'active' or now() < a.starts_at or now() >= a.ends_at then
    raise exception 'Auction is not active';
  end if;

  minimum := greatest(coalesce(a.current_bid,a.starting_price),a.starting_price) + a.bid_increment;
  if p_amount < minimum then raise exception 'Bid must be at least %',minimum; end if;

  insert into public.auction_bids(auction_id,bidder_id,amount)
  values(a.id,(select auth.uid()),p_amount) returning * into b;

  update public.auctions
  set current_bid=p_amount,updated_at=now()
  where id=a.id;

  return b;
end;
$func$;

revoke all on function public.place_bid(uuid,numeric) from public;
grant execute on function public.place_bid(uuid,numeric) to authenticated;

insert into public.categories(name,slug,description) values
('AI','ai','Artificial intelligence and machine learning products'),
('SaaS','saas','Software products delivered as a service'),
('Developer Tools','developer-tools','Tools and infrastructure for builders'),
('Productivity','productivity','Tools that help people work better'),
('Finance','finance','Fintech and financial products'),
('Education','education','Learning and education products'),
('Design','design','Design, creative and visual products'),
('Gaming','gaming','Games and gaming tools'),
('Marketing','marketing','Growth, content and marketing products'),
('Lifestyle','lifestyle','Products for everyday life')
on conflict(slug) do nothing;

insert into public.promotion_types(name,slug,description,default_price,default_duration_days)
values('Featured Promotion','featured','Featured project placement',999,7)
on conflict(slug) do nothing;

insert into public.promotion_positions(name,slug,description) values
('Homepage Hero','homepage-hero','Premium homepage hero placement'),
('Homepage Featured','homepage-featured','Featured project row placement'),
('Explore Featured','explore-featured','Featured placement on Explore'),
('Category Featured','category-featured','Featured placement within a category')
on conflict(slug) do nothing;

insert into public.settings(key,value,is_public) values
('featured_promotion_price','999',true),
('auction_starting_price','1499',true),
('auction_min_bid_increment','100',true),
('promotion_duration_days','7',true),
('auction_duration_hours','24',true)
on conflict(key) do nothing;
-- Lock bid writes behind the server-authoritative function.
revoke insert on public.auction_bids from anon,authenticated;

create or replace function public.place_bid(p_auction_id uuid,p_amount numeric)
returns public.auction_bids
language plpgsql
security definer
set search_path=public,pg_temp
as $func$
declare
  a public.auctions;
  b public.auction_bids;
  minimum numeric;
begin
  if (select auth.uid()) is null then
    raise exception 'Authentication required';
  end if;
  select * into a from public.auctions where id=p_auction_id for update;
  if not found then raise exception 'Auction not found'; end if;
  if a.status <> 'active' or now() < a.starts_at or now() >= a.ends_at then
    raise exception 'Auction is not active';
  end if;
  minimum := greatest(coalesce(a.current_bid,a.starting_price),a.starting_price) + a.bid_increment;
  if p_amount < minimum then raise exception 'Bid must be at least %',minimum; end if;
  insert into public.auction_bids(auction_id,bidder_id,amount)
    values(a.id,(select auth.uid()),p_amount) returning * into b;
  update public.auctions set current_bid=p_amount,updated_at=now() where id=a.id;
  return b;
end;
$func$;
revoke all on function public.place_bid(uuid,numeric) from public;
grant execute on function public.place_bid(uuid,numeric) to authenticated;

grant execute on function private.is_admin() to authenticated;

insert into storage.buckets(id,name,public)
values('project-assets','project-assets',true)
on conflict(id) do nothing;

create policy project_assets_public_read on storage.objects
for select to anon,authenticated
using(bucket_id='project-assets');

create policy project_assets_owner_insert on storage.objects
for insert to authenticated
with check(
  bucket_id='project-assets'
  and (storage.foldername(name))[1]=(select auth.uid())::text
);

create policy project_assets_owner_update on storage.objects
for update to authenticated
using(
  bucket_id='project-assets'
  and (storage.foldername(name))[1]=(select auth.uid())::text
)
with check(
  bucket_id='project-assets'
  and (storage.foldername(name))[1]=(select auth.uid())::text
);

create policy project_assets_owner_delete on storage.objects
for delete to authenticated
using(
  bucket_id='project-assets'
  and (storage.foldername(name))[1]=(select auth.uid())::text
);

create policy tags_member_insert on public.tags
for insert to authenticated
with check(length(name) between 1 and 40 and length(slug) between 1 and 50);
grant select on public.profiles,public.projects,public.project_tags,public.promotions to anon,authenticated;
grant insert on public.tags to authenticated;

create policy promotions_public_read on public.promotions
for select to anon,authenticated
using (
  status='active'
  or user_id=(select auth.uid())
  or private.is_admin()
);
create or replace function public.settle_auction(p_auction_id uuid)
returns table(auction_id uuid,winner_id uuid,winning_bid numeric)
language plpgsql
security definer
set search_path=public,pg_temp
as $func$
declare
  a public.auctions;
  bid public.auction_bids;
begin
  select * into a from public.auctions where id=p_auction_id for update;
  if not found then raise exception 'Auction not found'; end if;

  if a.status='active' and now() >= a.ends_at then
    select * into bid from public.auction_bids
    where auction_id=a.id
    order by amount desc, created_at asc
    limit 1;

    update public.auctions
    set status='settled',
        winner_id=bid.bidder_id,
        winning_bid=bid.amount,
        updated_at=now()
    where id=a.id;

    return query select a.id,bid.bidder_id,bid.amount;
  elsif a.status='settled' then
    return query select a.id,a.winner_id,a.winning_bid;
  else
    raise exception 'Auction cannot be settled in its current state';
  end if;
end;
$func$;

revoke all on function public.settle_auction(uuid) from public;
grant execute on function public.settle_auction(uuid) to authenticated;

insert into public.settings(key,value,is_public)
values('winner_payment_window_hours','24',true)
on conflict(key) do nothing;
create or replace function public.settle_auction(p_auction_id uuid)
returns table(auction_id uuid,winner_id uuid,winning_bid numeric)
language plpgsql
security definer
set search_path=public,pg_temp
as $func$
declare
  a public.auctions;
  bid public.auction_bids;
begin
  if coalesce(auth.role(),'') <> 'service_role' and not private.is_admin() then
    raise exception 'Admin authorization required';
  end if;

  select * into a from public.auctions where id=p_auction_id for update;
  if not found then raise exception 'Auction not found'; end if;

  if a.status='active' and now() >= a.ends_at then
    select * into bid from public.auction_bids
    where auction_id=a.id
    order by amount desc, created_at asc
    limit 1;

    update public.auctions
    set status='settled',
        winner_id=bid.bidder_id,
        winning_bid=bid.amount,
        updated_at=now()
    where id=a.id;

    return query select a.id,bid.bidder_id,bid.amount;
  elsif a.status='settled' then
    return query select a.id,a.winner_id,a.winning_bid;
  else
    raise exception 'Auction cannot be settled in its current state';
  end if;
end;
$func$;

revoke all on function public.settle_auction(uuid) from public,anon,authenticated;
grant execute on function public.settle_auction(uuid) to service_role;-- Product foundation additions: launch visuals and first-party visitor analytics.
alter table public.projects add column if not exists preview_images jsonb not null default '[]'::jsonb;
create table if not exists public.site_visitors (
  visitor_id text primary key,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  visit_count integer not null default 1
);
create index if not exists site_visitors_last_seen_idx on public.site_visitors(last_seen_at desc);
alter table public.site_visitors enable row level security;
revoke all on public.site_visitors from public, anon, authenticated;
create or replace function public.get_trending_project_ids(p_limit integer default 6)
returns table(project_id uuid, view_count bigint)
language sql
security definer
set search_path=public,pg_temp
as $func$
  select p.id,count(pv.id)::bigint
  from public.projects p
  left join public.project_views pv
    on pv.project_id=p.id and pv.created_at >= now()-interval '7 days'
  where p.status='published'
  group by p.id
  order by count(pv.id) desc, max(p.published_at) desc nulls last
  limit greatest(1,least(coalesce(p_limit,6),24));
$func$;
revoke all on function public.get_trending_project_ids(integer) from public,anon,authenticated;
grant execute on function public.get_trending_project_ids(integer) to anon,authenticated;
