import { Body, Button, Container, Heading, Hr, Html, Img, Link, Preview, Section, Text } from "@react-email/components";
import type { NewsletterBlock, NewsletterContent } from "@/lib/newsletter/types";

type Props={title:string;subject:string;content:NewsletterContent;archiveUrl:string;unsubscribeUrl:string;siteUrl:string};
const shell={fontFamily:"Arial,Helvetica,sans-serif",background:"#f5f4f0",color:"#171715",margin:0,padding:"32px 12px"};
const box={width:"100%",maxWidth:"620px",margin:"0 auto",background:"#fffefb",border:"1px solid #deddd7",borderRadius:"24px",overflow:"hidden"};
const pad={padding:"30px 34px"};
const muted={fontSize:"12px",lineHeight:"1.6",color:"#73716a"};
const absoluteUrl=(siteUrl:string,value:string)=>value.startsWith("http://")||value.startsWith("https://")?value:siteUrl.replace(/\/$/,"")+"/"+value.replace(/^\//,"");

function renderBlock(block:NewsletterBlock,siteUrl:string){
 if(block.type==="hero")return <Section style={pad}><Text style={{fontSize:10,letterSpacing:"0.14em",textTransform:"uppercase",color:"#86837b",margin:"0 0 9px"}}>{block.eyebrow}</Text><Heading style={{fontSize:36,lineHeight:1.04,letterSpacing:"-0.05em",margin:"0 0 12px"}}>{block.title}</Heading><Text style={{...muted,fontSize:14,margin:"0 0 18px"}}>{block.body}</Text>{block.imageUrl&&<Img src={block.imageUrl} alt="" width="552" style={{width:"100%",height:"auto",borderRadius:16,margin:"0 0 18px"}}/>}{block.ctaLabel&&block.ctaUrl&&<Button href={absoluteUrl(siteUrl,block.ctaUrl)} style={{background:"#171715",color:"#fff",borderRadius:999,padding:"12px 18px",fontSize:12,fontWeight:700}}>{block.ctaLabel}</Button>}</Section>;
 if(block.type==="text")return <Section style={pad}><Text style={{fontSize:10,letterSpacing:"0.14em",textTransform:"uppercase",color:"#86837b",margin:"0 0 7px"}}>{block.eyebrow}</Text><Heading as="h2" style={{fontSize:22,letterSpacing:"-0.035em",margin:"0 0 8px"}}>{block.title}</Heading><Text style={{...muted,fontSize:13,whiteSpace:"pre-line",margin:0}}>{block.body}</Text></Section>;
 if(block.type==="projects")return <Section style={pad}><Heading as="h2" style={{fontSize:22,letterSpacing:"-0.035em",margin:"0 0 14px"}}>{block.heading}</Heading>{block.items.map(item=><Section key={item.projectId} style={{borderTop:"1px solid #e5e3dc",padding:"16px 0"}}>{item.imageUrl&&<Img src={item.imageUrl} alt="" width="552" style={{width:"100%",height:"auto",borderRadius:14,marginBottom:10}}/>}<Link href={absoluteUrl(siteUrl,item.href)} style={{fontSize:16,fontWeight:750,color:"#171715",textDecoration:"none"}}>{item.title}</Link><Text style={{...muted,margin:"5px 0 0"}}>{item.tagline||item.excerpt}</Text></Section>)}</Section>;
 if(block.type==="community")return <Section style={pad}><Heading as="h2" style={{fontSize:22,letterSpacing:"-0.035em",margin:"0 0 14px"}}>{block.heading}</Heading>{block.items.map(item=><Section key={item.threadId} style={{borderTop:"1px solid #e5e3dc",padding:"16px 0"}}><Link href={absoluteUrl(siteUrl,item.href)} style={{fontSize:15,fontWeight:750,color:"#171715",textDecoration:"none"}}>{item.title}</Link><Text style={{...muted,margin:"5px 0 0"}}>{item.excerpt}</Text></Section>)}</Section>;
 return <Section style={{...pad,background:"#171715"}}><Heading as="h2" style={{fontSize:22,letterSpacing:"-0.035em",margin:"0 0 8px",color:"#fff"}}>{block.title}</Heading><Text style={{...muted,color:"#bebcb4",margin:"0 0 16px"}}>{block.body}</Text><Button href={absoluteUrl(siteUrl,block.url)} style={{background:"#fff",color:"#171715",borderRadius:999,padding:"12px 18px",fontSize:12,fontWeight:700}}>{block.label}</Button></Section>;
}

export function NewsletterEmail({title,subject,content,archiveUrl,unsubscribeUrl,siteUrl}:Props){
 return <Html lang="en"><Preview>{subject}</Preview><Body style={shell}><Container style={box}><Section style={{padding:"25px 34px 18px",borderBottom:"1px solid #deddd7"}}><Text style={{margin:0,fontSize:20,fontWeight:800,letterSpacing:"-0.05em"}}>Project<span style={{fontWeight:400}}>Hub</span></Text><Text style={{...muted,margin:"5px 0 0"}}>{title}</Text></Section>{content.blocks.map(block=>renderBlock(block,siteUrl))}<Section style={{padding:"22px 34px 30px"}}><Hr style={{borderColor:"#deddd7",margin:"0 0 17px"}}/><Text style={{...muted,fontSize:10,margin:"0 0 8px"}}>You’re receiving this because you subscribed to the ProjectHub Newsletter.</Text><Link href={absoluteUrl(siteUrl,archiveUrl)} style={{fontSize:10,color:"#171715",fontWeight:700}}>View on ProjectHub</Link><Text style={{...muted,fontSize:10,margin:"9px 0 0"}}><Link href={absoluteUrl(siteUrl,unsubscribeUrl)} style={{color:"#73716a"}}>Unsubscribe</Link></Text></Section></Container></Body></Html>;
}
